steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: deploy
    entrypoint: gcloud
    args:
      - run
      - deploy
      - fleetcommand-backend
      - --source=.
      - --region=asia-south2
      - --platform=managed
      - --allow-unauthenticated
      - --quiet

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1200s
